M-FeD/Fedoraware

SE-Owned/TeamFortress2/TeamFortress2/Features/Chams/Chams.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Chams/Chams.h, SE-Owned/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Misc/Misc.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Radar/Radar.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Vars.h, SE-Owned/TeamFortress2/TeamFortress2/Features/What/What.cpp
=> Fixed namebox, added edge jump bind, added fresnel chams (players)

SE-Owned/TeamFortress2/TeamFortress2/Features/Chams/Chams.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Chams/Chams.h
I misclicked and ruined the original SEOwnedPublic repo lmfao
=> fixed some chams issues

SE-Owned/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Vars.h, SE-Owned/TeamFortress2/TeamFortress2/Features/What/What.cpp, SE-Owned/TeamFortress2/TeamFortress2/Hooks/ClientHook/ClientHook.cpp
https://github.com/M-FeD/Fedoraware/issues/25
=> Add simple (and shit) pitch resolver

SE-Owned/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Vars.h, SE-Owned/TeamFortress2/TeamFortress2/Features/What/What.cpp
Possibly breaking https://docs.github.com/en/github/site-policy/github-community-guidelines#hate-speech-and-discrimination , we don't want the repo to be taken down by GitHub like cathook l0l
genuinely asking, can I have merge permissions
=> Remove offensive hateful speech

SE-Owned/TeamFortress2/TeamFortress2/Features/ChatInfo/ChatInfo.cpp
Found that the youtube bots changed one thing, so I said fuck it, if anyone sends it, they're marked.
Should've done that from the start, tho.
=> Fixed bot detection

SE-Owned/TeamFortress2/TeamFortress2/Features/Chams/Chams.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Chams/DMEChams.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Glow/Glow.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Misc/Misc.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Visuals/Visuals.cpp, SE-Owned/TeamFortress2/TeamFortress2/SDK/Includes/Classes.h, SE-Owned/TeamFortress2/TeamFortress2/SDK/Main/KeyValues/KeyValues.cpp, SE-Owned/TeamFortress2/TeamFortress2/SDK/Main/KeyValues/KeyValues.h, SE-Owned/TeamFortress2/TeamFortress2/SDK/SDK.h
duh. you've got actual keyvalues.
=> make spook happy with keyvalues

SE-Owned/TeamFortress2/TeamFortress2/Features/Misc/Misc.cpp
=> not ghetto i promise..

SE-Owned/TeamFortress2/TeamFortress2/Features/Glow/Glow.cpp
=> fix viewmodels breaking

SE-Owned/TeamFortress2/TeamFortress2.vcxproj, SE-Owned/TeamFortress2/TeamFortress2/DLLMain.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/ChatInfo/ChatInfo.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Vars.h, SE-Owned/TeamFortress2/TeamFortress2/Features/What/What.cpp
forgot about adding it to the array and fixed local player being marked as one as well.
=> re-add bot detection (again)

SE-Owned/TeamFortress2/TeamFortress2/Features/ChatInfo/ChatInfo.cpp
=> i need sleep

SE-Owned/TeamFortress2/TeamFortress2/Hooks/ClientModeHook/ClientModeHook.cpp, SE-Owned/TeamFortress2/TeamFortress2/Hooks/EngineHook/EngineHook.cpp
i dont know how c plu splus works. i dont know how tf2 fedoraware works.
=> dt but like it dt's when not using autoshoot

SE-Owned/TeamFortress2/TeamFortress2/Hooks/EngineHook/EngineHook.cpp
=> lol defo no crash

SE-Owned/TeamFortress2/TeamFortress2/Hooks/EngineHook/EngineHook.cpp
god i hate kamiii its all his fault his voice gives me mental issues
=> me erm emem em e mi hate kamiii

SE-Owned/TeamFortress2/TeamFortress2.vcxproj, SE-Owned/TeamFortress2/TeamFortress2.vcxproj.user, SE-Owned/TeamFortress2/TeamFortress2/Features/ChatInfo/ChatInfo.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Vars.h, SE-Owned/TeamFortress2/TeamFortress2/Features/Visuals/Visuals.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/What/ImGui/imgui.h, SE-Owned/TeamFortress2/TeamFortress2/Features/What/ImGui/imgui_demo.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/What/ImGui/imgui_draw.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/What/What.cpp, SE-Owned/TeamFortress2/TeamFortress2/Hooks/EngineVGuiHook/EngineVGuiHook.cpp, SE-Owned/TeamFortress2/TeamFortress2/SDK/SDK.h
=> Added oxyGodmode's imgui style to style editor | Added customizability to the default dt bar

SE-Owned/TeamFortress2/TeamFortress2/Hooks/EngineHook/EngineHook.cpp
fix crash where you would crash after joining match cuz local player was null :trollface: 
here is epic proof!!
:trollface: :trollface: :trollface: :trollface: :trollface:
=> crash fix :trollface: :trollface: :trollface:

SE-Owned/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Vars.h, SE-Owned/TeamFortress2/TeamFortress2/Features/What/What.cpp, SE-Owned/TeamFortress2/TeamFortress2/Hooks/ClientModeHook/ClientModeHook.cpp, SE-Owned/TeamFortress2/TeamFortress2/Hooks/EngineHook/EngineHook.cpp
Recharge while dead will automatically fill your DoubleTap bar if you are dead. I also made some changes to AutoRecharge alongside M-FeD, these are being able to toggle AutoRecharge and also simplifying a lil bit the code of it
=> Add Recharge while dead and toggleable AutoRecharge

README.md
its a normal zip file, no need for third party software :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:
=> fix in readme

README.md
=> fuck gameowner

README.md
:trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: hi :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: …
=> :trollface: readme funny edit hi bro :trollface: :trollface: :trollface: 

SE-Owned/TeamFortress2/TeamFortress2/Features/What/ImGui/imgui_draw.cpp
=> thanks for the free watermark oxy

SE-Owned/TeamFortress2/TeamFortress2/DLLMain.cpp, SE-Owned/TeamFortress2/TeamFortress2/Hooks/EngineVGuiHook/EngineVGuiHook.cpp
:trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface:
=> Optimize Steam RPC

SE-Owned/TeamFortress2/TeamFortress2/Features/Console/Console.cpp
https://cdn.discordapp.com/attachments/886157346898845749/898680965705113690/OxyTocin-main.zip
=> pro tip: never let oxy touch your code

SE-Owned/TeamFortress2/TeamFortress2/Features/What/What.cpp
=> pissing off everyone who already has configs with .seo filename

SE-Owned/TeamFortress2/TeamFortress2/DLLMain.cpp
=> :trollface:

.github/workflows/msbuild.yml
=> HutchyBean has fixed it so epic so epic woohoo 

SE-Owned/TeamFortress2/TeamFortress2/Hooks/FireBullets/FireBullets.cpp, SE-Owned/TeamFortress2/TeamFortress2/Hooks/Hooks.cpp, SE-Owned/TeamFortress2/TeamFortress2/SDK/Main/BaseCombatWeapon/BaseCombatWeapon.h, SE-Owned/TeamFortress2/TeamFortress2/SDK/Main/BaseEntity/BaseEntity.h
left out return addresses because cba, inventory will almost always be e8 anyway.
=> resolved most e8 calls

SE-Owned/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/PlayerList/PlayerList.cpp, SE-Owned/TeamFortress2/TeamFortress2/Features/Vars.h, SE-Owned/TeamFortress2/TeamFortress2/Features/What/What.cpp, SE-Owned/TeamFortress2/TeamFortress2/Hooks/ClientHook/ClientHook.cpp, SE-Owned/TeamFortress2/TeamFortress2/SDK/Main/GlobalInfo/GlobalInfo.h
Added a simple resolver that can be configured in the playerlist once enabled.  I've also removed the default pitch resolver and added an "Auto" option instead.
It looks like this:
=> Added epic pitch and yaw resolvers

Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Vars.h
Added two new AntiAim modes:
- Random
- Spin (with custom spin speed)
and a confirm dialog when overriding or removing configs.
=> Added more AA options and more

Fedoraware/TeamFortress2/TeamFortress2/Hooks/ClientHook/ClientHook.cpp, Fedoraware/TeamFortress2/TeamFortress2/Hooks/ClientModeHook/ClientModeHook.cpp
=> Fixed Fakelag

Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Misc/Misc.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Misc/Misc.h
Draws your server side hitboxes, only used in deathpole to debug fakelag & antiaim, kind of pointless outside of that.
=> Add server hitbox (local srv only for debug)

Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Misc/Misc.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Vars.h, Fedoraware/TeamFortress2/TeamFortress2/Features/Visuals/Visuals.cpp, Fedoraware/TeamFortress2/TeamFortress2/Hooks/ClientModeHook/ClientModeHook.cpp, Fedoraware/TeamFortress2/TeamFortress2/Utils/Utils.h, README.md
- Fixed issue #199 
- Fixed skybox not being saved in a config
- Added more chat spam (Lmaobox, Cathook)
- Added more shortcuts in the menu bar
- Added custom Rage Retry health limit
- Various fixes and improvements
=> Various additions and improvements

Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/PlayerList/PlayerList.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Vars.h, Fedoraware/TeamFortress2/TeamFortress2/Hooks/ClientHook/ClientHook.cpp, Fedoraware/TeamFortress2/TeamFortress2/Hooks/ClientHook/ClientHook.h, Fedoraware/TeamFortress2/TeamFortress2/Hooks/Hooks.cpp
- Added chat censor: Clears the chat when certain keywords (hack, cheat etc.) are detected
- Switched to relative aim resolver modes (Forward, Backward, Left, Right) instead of cardinal directions
=> Added chat censor and relative aim resolver

Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Vars.h, Fedoraware/TeamFortress2/TeamFortress2/Hooks/ClientModeHook/ClientModeHook.cpp, Fedoraware/TeamFortress2/TeamFortress2/Hooks/EngineHook/EngineHook.cpp
-random, on movement, and plain fakelag #200 
-decluttered fakelag options
=> changes to fakelag

Fedoraware/TeamFortress2/TeamFortress2/DLLMain.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/ChatInfo/ChatInfo.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/ConfigManager/ConfigManager.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Misc/Misc.cpp, Fedoraware/TeamFortress2/TeamFortress2/Features/Misc/Misc.h, Fedoraware/TeamFortress2/TeamFortress2/Features/Vars.h, Fedoraware/TeamFortress2/TeamFortress2/Hooks/ClientModeHook/ClientModeHook.cpp, Fedoraware/TeamFortress2/TeamFortress2/Hooks/ClientModeHook/ClientModeHook.h, Fedoraware/TeamFortress2/TeamFortress2/Hooks/EngineHook/EngineHook.cpp, Fedoraware/TeamFortress2/TeamFortress2/Hooks/EngineHook/EngineHook.h, Fedoraware/TeamFortress2/TeamFortress2/Hooks/Hooks.cpp, Fedoraware/TeamFortress2/TeamFortress2/SDK/Interfaces/EngineClient/EngineClient.h, Fedoraware/TeamFortress2/TeamFortress2/Utils/Utils.h
-added mvm instant respawn
-added listener for vote_started (cant believe i didnt do this when i put the code that needed it in;;;)
-fixed fakelag indicator (vSorry for breaking)
-fixed error spam from cathook pasted code (gcc escape)
-fixed cheat not building because of a poor merge
=> mvm instant respawn, remove fire_delay (tried lol)
